name: skin_app_migration
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8


  #screen utility
  flutter_screenutil: ^5.9.3

  #  form builders and validators
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0

  #firebase
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_database: ^12.0.0
  firebase_messaging: ^16.0.0
  google_sign_in: ^6.3.0

  #  lottie for animation
  lottie: ^3.3.1

  #  Internet connectivity
  internet_connection_checker: ^3.0.1
  connectivity_plus: ^6.1.4

  #state management
  provider: ^6.1.5

  #  internet image
  cached_network_image: ^3.4.1

  #  fetch metadata from url
  metadata_fetch: ^0.4.2

  #url launcher
  url_launcher: ^6.3.2

  #date package
  intl: ^0.20.2
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  flutter_svg: ^2.2.0

  #  content sharing
  flutter_sharing_intent: ^1.1.1
  receive_intent: ^0.2.7

  # sqflite
  sqflite: ^2.4.2

  # logger
  logger: ^2.6.1


  #Permission handler
  permission_handler: ^12.0.1

  csv: ^6.0.0
  open_filex: ^4.7.0


  path_provider: ^2.1.5
  path: ^1.9.1

  #Placeholder
  shimmer: ^3.0.0

  flutter_local_notifications: ^19.4.0
  http: ^1.5.0

  easy_image_viewer: ^1.5.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For

  assets:
    - assets/lottie/
    - assets/icons/
    - assets/svgs/
    - assets/logo/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 500

